export * from '@/schema/article.js'
export * from '@/schema/area.js'
export * from '@/schema/museum.js'
export * from '@/schema/spot.js'
export * from '@/schema/tag.js'
export * from '@/schema/user.js'
export * from '@/schema/audio.js'
export * from '@/schema/picture.js'
export * from '@/schema/guide.js'
export * from '@/schema/event.js'
export * from '@/schema/auth.js'
export * from '@/repository/museum/article.js'
export * from '@/repository/museum/area.js'
export * from '@/repository/museum.js'
export * from '@/repository/museum/spot.js'
export * from '@/repository/museum/tag.js'
export * from '@/repository/museum/audio.js'
export * from '@/repository/museum/picture.js'
export * from '@/repository/museum/guide.js'
export * from '@/repository/museum/event.js'
export * from '@/repository/user.js'
export * from '@/repository/auth.js'

export type FetchLike = typeof fetch